# fly.toml app configuration file generated for full-stack-open-pokedex-polished-pond-5762 on 2025-02-08T07:38:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-polished-pond-5762'
primary_region = 'fra'

[build]

[env]
  PORT = "3000"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "2s"
  path = "/health"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
