name: Deployment pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps
      - run: npm run eslint
      - run: npm test
      - name: Run e2e tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: e2e-reports
          path: playwright-report/
          retention-days: 30

      - name: failing succesfully
        run: exit 1

      - if: ${{ github.event_name == 'push' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        if: ${{ github.event_name == 'push' }}
        run: |
          npm run build
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Discord webhook failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: FSO Discord Notifier
          avatarUrl: https://upload.wikimedia.org/wikipedia/fi/thumb/2/21/Helsingin_yliopisto.svg/1280px-Helsingin_yliopisto.svg.png
          details: 'Deployment/merge failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message) ,'#skip' )}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Discord webhook failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          username: FSO Discord Notifier
          avatarUrl: https://upload.wikimedia.org/wikipedia/fi/thumb/2/21/Helsingin_yliopisto.svg/1280px-Helsingin_yliopisto.svg.png
          details: 'Tagging failed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  notifications:
    needs: [tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Discord webook
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          username: FSO Discord Notifier
          color: '#00ff00'
          avatarUrl: https://upload.wikimedia.org/wikipedia/fi/thumb/2/21/Helsingin_yliopisto.svg/1280px-Helsingin_yliopisto.svg.png
          description: |
            - **Repository:** ${{ github.event.repository }}
            - **Compare changes:** ${{ github.event.compare }}
            - **Hash:** ${{ github.event.after }}
            - **Head commit message:** ${{ github.event.head_commit.message }}

          details: |
            --------------------------------------------------------------
            - **Committer:** ${{github.event.head_commit.author.username}}
            - **Pusher:** ${{github.event.pusher.name}}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
